# Generated by Django 4.2.7 on 2023-12-05 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="user",
            table="User",
        ),
    ]
