# Generated by Django 4.2.7 on 2023-11-29 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                ("uid", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(default="张三", max_length=10)),
                ("age", models.IntegerField(default=20)),
            ],
        ),
    ]
