# Generated by Django 4.2.7 on 2023-11-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Userapp",
            fields=[
                ("uid", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(default="张三", max_length=30)),
                ("age", models.IntegerField(default=18)),
                ("salary", models.FloatField(default=5000, max_length=6)),
                ("data", models.DateTimeField(auto_now_add=True)),
                ("info", models.TextField(blank=True)),
            ],
        ),
    ]
